version: "3"
networks:
  kafka:
    external:
      name: kafka

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    restart: always
    deploy:
     resources:
        limits:
          cpus: '0.1'
          memory: "256M"       
    ports:
      - '2181:2181'
    networks:
     - kafka
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    deploy:
     resources:
        limits:
          cpus: '0.1'
          memory: "512M"
    restart: always
    ports:
      - '9092:9092'
    networks:
     - kafka
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_KRAFT_CLUSTER_ID=local
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
    depends_on:
      - zookeeper
